### ISSUE TITLE
PDB fetch function not working

### ISSUE THREAD

**Issue by SkBlaz** [gjbekker/molmil#2]
Around 6 hours ago molmil stopped fetching PDBs from PDB. Is this a temporary issue?

**Comment by gjbekker** [comment]
Due to a misconfiguration of PDBj's DNS configuration, the website was not accessible and thus the PDB entries could not be fetched. This problem has now been corrected. I apologize for the inconvenience it might have caused.

**Comment by SkBlaz** [comment]
Thank you very much! Just so you know, we are implementing molmil into a
new platform, it works perfectly, there is only one more minor problem -
labels - are there any implementable presets for them we missed?

Greets,

Blaz
