### ISSUE TITLE
Labeling functionality

### ISSUE THREAD

**Issue by gjbekker** [gjbekker/molmil#3]
@SkBlaz requested labeling functionality for Molmil in issue #2.

The new function `molmil.addLabel` adds an arbitrary label somewhere in the canvas.
The size of the text is zoom-level independent, but can be modified by the user.

<b>`molmil.addLabel(text, settings, soup)`</b>
- `text`: content for the label (required)
- `settings`:
  - `xyz`: array determining the position of the label in 3D space (required)
  - `dx`: offset along x axis in screen space (default value `0.0`)
  - `dy`: offset along y axis in screen space (default value `0.0`)
  - `dz`: offset along z axis in screen space (default value `0.0`)
  - `fontSize`: size of the text (default value `20.0`)
  - `color`: rgb color of the text (default value `[0, 255, 0]`)
- `soup`: molmil.viewer object to load the data into (optional in command-line mode)

Usage example:

``` javascript
  molmil.loadPDB("1crn", null, null, canvas.molmilViewer);

  var chain = canvas.molmilViewer.structures[0].chains[0];
  var CA = chain.molecules[0].CA;
  var xyz = [chain.modelsXYZ[0][CA.xyz], chain.modelsXYZ[0][CA.xyz+1], chain.modelsXYZ[0][CA.xyz+2]];

  molmil.addLabel("Thr1", {xyz: xyz, dz: 2}, canvas.molmilViewer);

  var CA = chain.molecules[chain.molecules.length-1].CA;
  var xyz = [chain.modelsXYZ[0][CA.xyz], chain.modelsXYZ[0][CA.xyz+1], chain.modelsXYZ[0][CA.xyz+2]];        
  molmil.addLabel("Asn46", {xyz: xyz, dz: 2, color: [255, 0, 0], fontSize: 40}, canvas.molmilViewer);
```

This shows two labels; one for Thr1 and one for Asn46, where the latter has a font size of 40 (2x larger than the former) and is colored red.
In both cases `dz` is set to 2.0, meaning that the label is positioned 2A closer to the camera compared to the base position, which equals the CA atom in both cases.
This means that the label is positioned in front of the CA atom in any viewing direction.

The above commands produces the following labels:
![labels](https://cloud.githubusercontent.com/assets/15721196/19219150/ba24b3b0-8e46-11e6-9d20-2d954501a170.png)

**Comment by rdecapomaranca** [comment]
I would like to second this request. Label function is something that is really missing in this otherwise great  molecular viewer.

**Comment by SkBlaz** [comment]
super! In dej tanovo verzijo probej, nevem ce je v prejsnji delal, sm dal
minuto nazaj gor

**Comment by rdecapomaranca** [comment]
It is working! :D

**Comment by gjbekker** [comment]
I have made some further improvements to the labeling functionality (including creating & modifying the labels via the graphical interface) and I have committed these modifications to the repo. Finally, I have prepared a <a target="_blank" href="http://gjbekker.github.io/molmil/examples/repo-test.html#molmil.loadPDB('1crn'); var chain = cli_soup.structures[0].chains[0]; var CA = chain.molecules[0].CA; var xyz = [chain.modelsXYZ[0][CA.xyz], chain.modelsXYZ[0][CA.xyz+1], chain.modelsXYZ[0][CA.xyz+2]]; molmil.addLabel('Thr1', {xyz: xyz, dz: 2}); var CA = chain.molecules[chain.molecules.length-1].CA; var xyz = [chain.modelsXYZ[0][CA.xyz], chain.modelsXYZ[0][CA.xyz+1], chain.modelsXYZ[0][CA.xyz+2]]; molmil.addLabel('Asn46', {xyz: xyz, dz: 2}); var all = molmil.calcCenter(chain); molmil.addLabel('1crn', {xyz: all[0], dx:0, dy:all[1]+2.0+2.0, dz:0.0, fontSize: 40, color: [255, 0, 0]});">demo</a> to try out the new functionality.

The following is the code (which is embedded in the URL) that is executed in the above demo:
```Javascript
molmil.loadPDB('1crn'); 
var chain = cli_soup.structures[0].chains[0]; 

var CA = chain.molecules[0].CA; 
var xyz = [chain.modelsXYZ[0][CA.xyz], chain.modelsXYZ[0][CA.xyz+1], chain.modelsXYZ[0][CA.xyz+2]]; 
molmil.addLabel('Thr1', {xyz: xyz, dz: 2}); 

var CA = chain.molecules[chain.molecules.length-1].CA; 
var xyz = [chain.modelsXYZ[0][CA.xyz], chain.modelsXYZ[0][CA.xyz+1], chain.modelsXYZ[0][CA.xyz+2]]; 
molmil.addLabel('Asn46', {xyz: xyz, dz: 2}); 

var all = molmil.calcCenter(chain); 
molmil.addLabel('1crn', {xyz: all[0], dx:0, dy:all[1]+2.0+2.0, dz:0.0, fontSize: 40, color: [255, 0, 0]});
```

![labels](https://cloud.githubusercontent.com/assets/15721196/19259317/5b322e8e-8fbb-11e6-8c8f-02980ba30182.png)

**Comment by SkBlaz** [comment]
Hello! Thanks for the improvements! We implemented the labeling functionality into our system, yet some problems remain, namely: while rotating the molecule, labels sometimes disappear and reappear at random, sometimes molmil instead of labels draws long lines all across canvas - I've seen such behavior once, the underlying matrices weren't rotating correctly. Is there anything you can do regarding this problem?

Thanks again

**Comment by gjbekker** [comment]
I never ran into the problems you described, so could you please provide me with some examples (i.e. code) where the issues occur? That way I can try to debug the problems using these examples. 

BTW, which version of Molmil are you using; the raw code from the repository (updated) or the minified version in the gh-pages (not yet updated)?

**Comment by rdecapomaranca** [comment]
We are working with the updated repository (only molmil.selectionFocus function is from the old commit-from September 2016).
The problem occurs when trying to label molecule (chain 0, molecule 7) on PDB 3kej in Spacefill style with following label settings: {xyz: xyz, fontSize: 25, color: [255, 255, 0]}, where xyz = [chain.modelsXYZ[0][CA.xyz], chain.modelsXYZ[0][CA.xyz+1], chain.modelsXYZ[0][CA.xyz+2]] and CA = mol.CA.

This reproduces the following results under different rotations.
![covering_up](https://cloud.githubusercontent.com/assets/7722193/19430940/97c93b86-9456-11e6-9d09-bdd22a8a71ea.png)
![laser_effect](https://cloud.githubusercontent.com/assets/7722193/19430939/97c051b0-9456-11e6-9bb2-b2732d288c98.png)

And sometimes the label is not even seen.

**Comment by gjbekker** [comment]
Thank you for the examples.

In the first image, the issue is caused how the function is used. With these settings, the label (a flat rectangular object with a texture attached) is placed on the exact same position as the CA atom. The geometry for the CA atom (and the other atoms surrounding it) are sometimes closer to the camera than the label and thus the label becomes obscured.

In my example above, I set dz=2, which means that the label is positioned 2 Angstrom closer to the camera with respect to the original position. This means that independent of the position, the label would be always be shown in front of the CA atom it was created for.

This however only deals with the CA atom and not the surrounding atoms of the same residue. In the same example I used the function `molmil.calcCenter` for the chain, but this can also be used for residues such as <a href="http://gjbekker.github.io/molmil/examples/repo-test.html#molmil.loadPDB('3kej'); var chain = cli_soup.structures[0].chains[0]; var CA = chain.molecules[6].CA; molmil.displayEntry(CA.molecule, molmil.displayMode_Spacefill, true); var all = molmil.calcCenter(CA.molecule); molmil.addLabel('rs74....569', {xyz: all[0], dz: all[1]+2.0});">here</a>:

```javascript
molmil.loadPDB('3kej'); 
var chain = cli_soup.structures[0].chains[0]; 

var CA = chain.molecules[6].CA; 
molmil.displayEntry(CA.molecule, molmil.displayMode_Spacefill, true); 
var all = molmil.calcCenter(CA.molecule); 
molmil.addLabel('rs74....569', {xyz: all[0], dz: all[1]+2.0}); 
```

In case you prefer the label to always be displayed on the screen independent of the depth, I could add an option for that too.

I have not seen the second issue before. I'll look into that a bit more. In case you have some more information or feedback, please let me know.

**Comment by rdecapomaranca** [comment]
I tried using calcCenter function and it seems to be a problem of focus centre.
In the above images the first is taken with the default centre (focus of the whole structure) and the second one with centre in molecule on which the label is appended to.
![default_focus](https://cloud.githubusercontent.com/assets/7722193/19435936/b5abbf7c-946d-11e6-8210-b4a8e8390acb.png)
![focus_on_atom](https://cloud.githubusercontent.com/assets/7722193/19435937/b5aeb01a-946d-11e6-8a2f-1621a2e36a14.png)

Aside from that, the label while focused on selected molecule only shows if your zoom close enough (i don't know if this was meant to be this way or not).

**Comment by gjbekker** [comment]
The size of the text should remain the same, independent of the zoom level. If you zoom out, the label suddenly disappears?

**Comment by SkBlaz** [comment]
Yes, that's exactly what happens.

**Comment by rdecapomaranca** [comment]
And the rotation matrices should change depending on current focus point (aka centre of rotation).
Currently (as far as I can see) the centre of rotation for label is fixed and independent of centre of rotation of structure (see the last post with images; the second image is fine, though label sometimes disappears during rotation; while in first image the label is deformed and when structure is rotated it dances all over the place)

**Comment by gjbekker** [comment]
The weirdness with the jumping labels was apparently caused because a vec3 wasn't initialized in the shader code, where this was not giving any problems on windows machines.
