### ISSUE TITLE
Alpha channel in RGBA

### ISSUE THREAD

**Issue by rdecapomaranca** [gjbekker/molmil#5]
This is more of a request than an issue. I was wondering if it would be (or maybe it already is) possible to modify alpha channel of rgba, specifically for surfaces. I have already found where to change the color of the surface and the selected color is decided with rgba color space. The only problem is that changing the alpha channel has no effect on transparency at all.
I changed the color of surface by changing surf.rgba in molmil.geometry.generateSurfaces function.

**Comment by SkBlaz** [comment]
Hello. I appear to have the same problem with the transparency setting. Is there anything that could be done? So, rgb works, but rgba doesn't

**Comment by gjbekker** [comment]
I've added automated detection of alpha to the surface functionality, so that the following now <a href="http://gjbekker.github.io/molmil/examples/repo-test.html#molmil.loadPDB('1crn');molmil.displayEntry(molmil.cli_soup.structures,molmil.displayMode_ChainSurfaceCG,true);molmil.colorEntry(molmil.cli_soup.structures,molmil.colorEntry_Custom,[255,0,0,128],true);molmil.loadPDB('1crn');">works</a>:

```javascript
// load 1crn
molmil.loadPDB('1crn');

// display as a semi-transparent surface red surface
molmil.displayEntry(molmil.cli_soup.structures,molmil.displayMode_ChainSurfaceCG,true);
molmil.colorEntry(molmil.cli_soup.structures,molmil.colorEntry_Custom,[255,0,0,128],true);

// load 1crn once more and render it as a cartoon (default)
molmil.loadPDB('1crn');
```

![rgba](https://cloud.githubusercontent.com/assets/15721196/20082279/197e8f3a-a598-11e6-8281-bf828bd25358.png)

**Comment by rdecapomaranca** [comment]
Thank you. It works wonderfully. Also labels are now working without any glitches.

**Comment by rdecapomaranca** [comment]
I have found a glitch in the alpha channel for surface. When rotating the structure it seems that the surface is always on top, resulting in a glitch seen when comparing the two below images.
On the side view the surface works perfectly and it is clearly seen which part of the structure surface covers and which parts are outside the surface. While in the front view it seems as if more of the structure is covered by the surface.
![side_view](https://cloud.githubusercontent.com/assets/7722193/20103341/dc006796-a5c9-11e6-8063-92ac67a7c480.png)
![front_view](https://cloud.githubusercontent.com/assets/7722193/20103340/dbf673d0-a5c9-11e6-9e56-9b7e55f8be3c.png)

**Comment by gjbekker** [comment]
Thank you for the bug report. This should be solved now.

**Comment by rdecapomaranca** [comment]
Thank you. Now it works.
