### ISSUE TITLE
Visualization of interactions such as hydrogen bonds

### ISSUE THREAD

**Issue by janezkonc** [gjbekker/molmil#6]
Please add function for seeing interactions as dashed lines so that we can visualize interactions. molmil.geometry.generator should be the function :-)

**Comment by gjbekker** [comment]
I have added the following functions to Molmil (5731bfc9e161b2519fe83a11275582813b93d823):
```javascript
renderHbonds(pairs, soup);
renderPIinteractions(pairs, soup);
renderSaltBridges(pairs, soup);
```

Here, pairs is an array of interactions, where each interaction consists of two coordinates, so:
```javascript
var pairs = [[[x1,y1,z1], [x2,y2,z2]], [[x3,y3,z3], [x4,y4,z4]]];
```
In the case of `renderHbonds`, each coordinate can be replaced by an `atomObject`.

I tried to mimic the style of PLIP as much as possible. Please try it out and let me know about any further improvements that should be made.

**Comment by janezkonc** [comment]
Dear Gert-Jan,

Thank you so much !

We will test this asap!

Regards,
Janez

**Comment by rdecapomaranca** [comment]
Adding bonds works perfectly. Now I would like to know how I can erase the created bond?

**Comment by gjbekker** [comment]
I have modified the functions `renderHbonds`, `renderPIinteractions` and `renderSaltBridges` to return the programs used to render the geometry. If you call `soup.renderer.removeProgram(program_to_delete);` the program should be deleted from the renderer. Please note that you still need to tell molmil to issue a new draw to update the screen by using `soup.renderer.canvas.update = true;`.

**Comment by janezkonc** [comment]
Thanks a lot for sharing the code to erase h-bonds. We'll test this asap!

**Comment by rdecapomaranca** [comment]
We have tried the code and it works.
Thank you.
