### ISSUE TITLE
REST API problem?

### ISSUE THREAD

**Issue by SkBlaz** [gjbekker/molmil#8]
Hello,

we use the molmil tool extensively in our application (genprobis.insilab.org). The molmil REST address suddenly does not seem to be the correct one anymore, i.e., the link:

https://ipr.pdbj.org/rest/displayPDBfile?format=mmjson-all&id=3kej

does not seem to work anymore (at least that is what the molmil seems to call)

You can inspect the error in-place here:
http://genprobis.insilab.org/?query=3kejA

Thank you very much for any feedback.

**Comment by gjbekker** [comment]
ipr.pdbj.org points to our old server, which is no longer being used (and updated). Could you modify your version of Molmil so that the URL points to the top domain instead, so that it becomes:
https://pdbj.org/rest/displayPDBfile?format=mmjson-all&id=3kej

**Comment by SkBlaz** [comment]
Thank you very much, this fixed the issue.
